spring:
  application:
    name: servicio-zuul-server
    
server:
  port: 8090
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    productos:
      #Aqui indicas el nombre del microservicio a configurar
      service-id: servicio-productos
      #Con esto indicas que todas las rutas del microservicio de productos se les va a poner un prefijo 
      path: /api/productos/**
    items:
      service-id: servicio-items
      path: /api/items/**
    usuarios:
      service-id: servicio-usuarios
      path: /api/usuarios/**
#Con esto se configura un timeout para hystrix, el cual debe ser mayor que el de ribbon
#ya que, según la documentación de spring cloud, hystrix "envuelve" a ribbon por lo tanto
#hystrix debe esperar más tiempo que ribbon
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
#Con esto se configura un timeout para ribbon
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000